server:
  port: 8765
spring:
  application:
    name: service-openfeign

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间(毫秒)
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间(毫秒)  默认等待时间是1秒
  ConnectTimeout: 5000

  logging:
    level:
      # feign日志以什么级别监控哪个接口
      com.cloud.service.PaymentFeignService: debug

hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

feign:
  #开启服务降级
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://EurekaServer8080.com:8080/eureka/,http://EurekaServer8081.com:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'