spring:
  application:
    name: eureka-client-producer

server:
  port: 8001

eureka:
  instance:
    # 采用IP注册
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    #eureka.client.serviceUrl.defaultZone 的地址就是我们之前启动的 Eureka 服务的地址，
    # 在启动的时候需要将自身的信息注册到 Eureka 中去。
    serviceUrl:
      defaultZone: http://EurekaServer8080.com:8080/eureka/,http://EurekaServer8081.com:8081/eureka/
