spring:
  application:
    name: eureka-server

server:
  port: 8081

eureka:
  instance:
    hostname: EurekaServer8081.com
    # 采用IP注册
    preferIpAddress: false
#    # 定义实例ID格式
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己,(生产者配置为true)
    register-with-eureka: true
    # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false(消费者配置为true)
    fetch-registry: true
    #指向另外一个注册中心  相互守望
    serviceUrl:
      defaultZone: http://EurekaServer8080.com:8080/eureka/
  server:
    enable-self-preservation: false             #关闭自我保护模式
    eviction-interval-timer-in-ms: 4000         #清理服务间隔4s，默认60*10000

